language: objective-c
osx_image: xcode8.3

script:
- xcodebuild clean build test -project "Swift.Binary.xcodeproj" -scheme SwiftBinary -sdk iphonesimulator10.3 -destination "OS=10.3,name=iPhone SE" ONLY_ACTIVE_ARCH=NO
